### ISSUE TITLE
weilong v10 ai how? (unrelated to this repository)

### ISSUE THREAD

**Issue by ghost** [lukeburong/cstimer#1]
I'm really sorry that I had to post this in this repository but I had absolutely no way to contact you about your pull request on the cstimer weilong v10 ai support.

First of all, thanks a lot for the pull request, I think you're a hero, and I really appreciate it. I don't know if people really appreciate your reverse engineering on that monster of a software.

I have a question though. In the pull request, I saw that the gyro part is empty. If you know, can you please tell us how the gyro part works? I have 0 idea about this whole reverse engineering stuff, and I tried il2cppdumper and ghidra and I can't understand a single thing that's happening in the code view.

**Comment by lukeburong** [comment]
Hi,

I will try to publish a write up describing the protocol in the next day or two (including gyro messages) - just be patient 😃

**Comment by ghost** [comment]
Thanks a lot for this. I will wait for the write up!

**Comment by lukeburong** [comment]
@hvven see my WIP write-up here: https://github.com/lukeburong/weilong-v10-ai-protocol

**Comment by ghost** [comment]
Again, thanks for this. We really appreciate it. I didn't want to make a comment again because it might be annoying to you but I'm just thankful.

After you're done if you want you could maybe post your work on reddit or something, like [this guy](https://www.reddit.com/r/Cubers/comments/1dkgu8b/i_reverse_engineered_the_qiyi_smartcube_protocol/) who re'd the Qiyi SC-S and let people know and get some upvotes. Just saying.

**Comment by lukeburong** [comment]
No problem - if you have any other questions feel free to reach out either via Discord (@lburong) or e-mail (on my profile). 😃
